# Generated by Django 5.1.6 on 2025-02-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('quantite', models.IntegerField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
