# Generated by Django 5.1.6 on 2025-02-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='description',
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(null=True, upload_to='Categorie'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
