# Generated by Django 5.1.6 on 2025-02-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_produits_description_categorie_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.categorie'),
        ),
    ]
